### ISSUE TITLE
TypeError in st.curation.threshold_isolation_distances 

### ISSUE THREAD

**Issue by teristam** [SpikeInterface/spiketoolkit#441]
When I am trying to use `threshold_isolation_distances`, I receive the following error

And the traceback is :

```
   126 
     127 sorting_ms4_curated=st.curation.threshold_isolation_distances(sorting_ms4_curated, recording,
---> 128     threshold=0.9, threshold_sign='less')
     129 print(sorting_ms4_curated.get_unit_ids())
     130 

~/miniconda3/envs/ms4/lib/python3.6/site-packages/spiketoolkit/curation/threshold_metrics.py in threshold_isolation_distances(sorting, recording, threshold, threshold_sign, num_channels_to_compare, max_spikes_per_cluster, **kwargs)
    840     isolaiton_distance = IsolationDistance(metric_data=md)
    841     threshold_sorting = isolaiton_distance.threshold_metric(threshold, threshold_sign, num_channels_to_compare,
--> 842                                                             max_spikes_per_cluster, **kwargs)
    843     return threshold_sorting
    844 

~/miniconda3/envs/ms4/lib/python3.6/site-packages/spiketoolkit/validation/quality_metric_classes/isolation_distance.py in threshold_metric(self, threshold, threshold_sign, num_channels_to_compare, max_spikes_per_cluster, **kwargs)
     47     def threshold_metric(self, threshold, threshold_sign, num_channels_to_compare, max_spikes_per_cluster, **kwargs):
     48         isolation_distances = \
---> 49         self.compute_metric(num_channels_to_compare, max_spikes_per_cluster, **kwargs)
     50         threshold_curator = ThresholdCurator(
     51             sorting=self._metric_data._sorting, metric=isolation_distances

~/miniconda3/envs/ms4/lib/python3.6/site-packages/spiketoolkit/validation/quality_metric_classes/isolation_distance.py in compute_metric(self, num_channels_to_compare, max_spikes_per_cluster, **kwargs)
     35             seed=seed,
     36             spike_cluster_subset=self._metric_data._unit_indices,
---> 37             verbose=self._metric_data.verbose,
     38         )[0]
     39         isolation_distances_list = []

TypeError: calculate_pc_metrics() missing 1 required positional argument: 'channel_locations'

```
I double check and make sure I am using the latest version of spiketookit from pip. The version is 0.7.2

Any idea how to resolve it? Thanks!

**Comment by alejoe91** [comment]
Can you try to install the master version? Otherwise you need spikemetrics==0.2.2

**Comment by teristam** [comment]
Thank you! It is working with spikemetrics==0.2.2.
